### PR TITLE
Issue 51: Solving retrieving OAuth token from repositories

### PR DESCRIPTION
**Pull request by jerrinss5**
Addressing retrieving OAuth token from repositories for all the registries.

### CODE REVIEW

**Comment by josephdrichard** [comment]
I tried out this change and am getting an error because my docker registry is on a non-default port.

It's getting ERROR 500 calling this:
`Calling: https://IP_ADDRESS:PORT/service/token?service=harbor-notary&scope=repository:IP_ADDRESS/jrichard/image-name:pull`
When the token is at:
`Calling: https://IP_ADDRESS:PORT/service/token?service=harbor-notary&scope=repository:IP_ADDRESS:PORT/jrichard/image-name:pull`

**Comment by sjhx** [comment]
I think this contains a better solution to no-auth notaries than https://github.com/IBM/portieris/commit/ceaa5ab87f7de74c92bf4ffeb2240e339915a0a2 and should have been merged in preference / first. Will work to have this merged next.

**Comment by sjhx** [comment]
There are a few things which are blocking this being merged:
1. Unit tests are broken, the problem is that the oauth.CheckAuthRequired which runs live in the unit test, actually contacting the named server, it really needs to interfaced/faked such that the unit test does not depend on external services and their responses. 
2. I am not sure that going un-authed to the external service on every request and then not using a potential good response if the best approach. 
3. No unit tests in the code added in helpers/oauth. 

@jerrinss5 What is your outlook for working on these issues?

**Comment by jerrinss5** [comment]
Thanks @sjhx  for reviewing it
1." it really needs to interfaced/faked such that the unit test does not depend on external services and their responses" - I will check and modify the test case, do you have any reference that I can follow for easier implementation?
2. "I am not sure that going un-authed to the external service on every request and then not using a potential good response if the best approach." - are suggesting to cache the response after initial un-authed request? Or are you mentioning some other flow for it? This approach was discussed here - https://github.com/IBM/portieris/issues/51#issuecomment-487395120
3. I will add unit tests for helpers/oauth and update the PR.

**Comment by sjhx** [comment]
1. in pkg/notary/notary.go it defines an interface which is implemented (and extended) by fakeNotary.go, if you maintain the CheckAuthRequired as a "oauth probe" only (reference to point 2) then you could make it part of that interface you would then setup the fake in the test for to respond appropriately, keeping helpers/oauth as static utiltity methods
2. Actually I was thinking that rather than being only an "oauth probe" with no potential to use a sucessful result, it could flow to notary make in inital requestwith no token and complete if successful, if auth is required based on an examination of the initial result then get the oauth token using the list of credentials and retry, maybe this amounts to the same thing as you said, also worth saying this is more debatable, 1. is priority 
3. appreciated

**Comment by jerrinss5** [comment]
@sjhx  - sorry couldn't make much progress on the test case earlier when I started. Was getting confused with the implementation and looks like the master branch has changed as well.

**Comment by sjhx** [comment]
Thanks for the effort here, closing in favor of the refactoring in https://github.com/IBM/portieris/pull/363

**Pull request closed without merging**
