### PR TITLE
Add keySecretNamespace policy option

### PR DESCRIPTION
**Pull request by lucaspalm**
This gives the ability to specify a namespace to look for the secret
specified in the `keySecret` field that will override the default behavior of just
looking in the namespace of the image being admitted.

### CODE REVIEW

**Comment by sjhx** [comment]
I like this approach better than the command line option, would it be in conventional or not to allow the keySecret to have path like `keySecret: namespaceforSecret/secretName` rather than as a separate property. Just think the policies are a getting  encumbered with too properties.

**Comment by lucaspalm** [comment]
Either way would work for us.  But in my opinion, having this as a separate field is the cleaner way.  1 field --> 1 value, just like you have been doing up to this point.  I wouldn't throw in a "special" field that allows for 2 values like this...

**Review by sjhx — APPROVED** [review]
looks good

**Comment by dnwake** [comment]
@lucaspalm. Thanks for submitting this fix.  Do you know whether there's any way to make use of it with a custom trust server?  We have been using the "trust" rather than "simple" option in our image policy in order to use our own trust server.

**Pull request merged**
