### PR TITLE
Use custom ca cert in oauth helper

### PR DESCRIPTION
**Pull request by josephdrichard**
This commit adds support for using the custom ca certificate
at "/etc/certs/ca.pem", similar to what is done inside of "notary.go"

Closes-bug: https://github.com/IBM/portieris/issues/99

Signed-off-by: Joseph Richard <joseph.richard@windriver.com>

### CODE REVIEW

**Comment by sjhx** [comment]
I notice that this will now create a new `client` on every request, not necessarily terrible, do you have any concerns @molepigeon @josephdrichard ?

**Comment by sjhx** [comment]
Should there be an effort to use the CA defined in trust.go rather than happening on the same file referenced separately in another file. Also might there be a problem if there are separate oauths for registry and notary with differend certificate chains.

**Comment by molepigeon** [comment]
I don’t feel that running separate clients is that big a deal, particularly at the kind of scale that we can expect Portieris to be running at. At higher loads it is a new object to be created, and there are nuances to running many clients. But since we’re always going to use the same cert chain that either exists or doesn’t, I wonder if we could do the work to create the client once and save it in a var like it used to be. We could retrieve it if it’s non-nil or create a new one if it is nil. @josephdrichard how do you feel about that?

**Comment by josephdrichard** [comment]
@sjhx I didn't want to use the ca defined in trust.go because oauth.go is in helpers.  I don't see any reason why there would ever be different certificate chains used inside the container.
@molepigeon From a performance impact, going out on the network to do the oauth request is an order of magnitude higher than the cost to create a new client to do this request, so I don't think there would be an issue here.  I don't think it would be any issue storing it either, but I would lean towards passing the client down to the oauth helper rather than storing it there.  I'm fine with any approach though.  Let me know which you prefer and I will update the pull request.

**Comment by molepigeon** [comment]
Good point about the network request, I'm happy to go with what you have already.

**Comment by sjhx** [comment]
@josephdrichard on the certificate chain, I am thinking of the case where you are running a private notary with a self-signed certificate and thus need a custom ca whereas the registry uses a public ca and you would be unable to use the default ca if you load the custom one. 
Anyhow I have no objection to merging this and addressing that, assuming its valid, and if it arrises, at another time.

**Pull request merged**
