### PR TITLE
Add basic metrics to portieris

### PR DESCRIPTION
**Pull request by guysports**
To allow the monitoring of portieris decisions for allow and deny of images,
prometheus metrics have been added as counters and are incremented when an
allow or deny decision is made.
They will be accessible from the portieris:8080/metrics endpoint

Additionally the logging for the Allow and Deny decisions has been enhanced
to list the container images and their tags and digests that the decision
was made for

Signed-off-by: Guy Barden <barden@uk.ibm.com>

### CODE REVIEW

**Comment by sjhx** [comment]
resolves: https://github.com/IBM/portieris/issues/162

**Review by sjhx — CHANGES_REQUESTED** [review]
I am struggling with the logging of image names with both tag and digest, if you have a digest then the tag is redundant and may be wrong, a tag being a mutable reference to a digest. Portieris replaces tags with digests so that different images cannot be admitted by changing registry tags. See https://github.com/IBM/portieris/issues/169. 

Incoming image references may have tag, digest or if perverse both, outgoing (and I suggest logs) will have only digest so that we have certainty about the image in question.  

Metrics needs at least a mention in doc/README.

**Review by sjhx — CHANGES_REQUESTED** [review]
I believe we also need to define the non TLS prom-metrics port in the service definition such that e.g. istio will be able to deal with it.

**Review by sjhx — CHANGES_REQUESTED** [review]
Needs at least a mention in the  README.md

**Comment by guysports** [comment]
Addresses the comments made.

1. Added a service port for the exposing metrics to the portieris service
2. Removed the tag information from the logging as the tag is not immutable and adds no value to the logging.
3. Added a section to the README to document the metrics available

**Review by sjhx — APPROVED** [review]
all concerns addressed

**Comment by jhart1685** [comment]
@guysports - Looking at the new log lines, it appears that the string `(image:digest)` hardcoded (in both the allow and deny cases). So the resulting log lines are like:
```text
controller.go:138] Allow for images (image:digest)
```

Was this intentional? Guess I was expecting to see details of the denied (or allowed) image in those log lines!

**Comment by guysports** [comment]
@jhart1685 My intention was to print a line that looked like
`Allow for image (image:digest) [image1:digest1] [image2:digest2]`

as per 
```
	for key := range denials {
		allowStr = fmt.Sprintf("%s [%s]", allowStr, key)
	}
	glog.Info(allowStr)
```

where the key is added to the denials map[string]string in the getPatchesForContainers() function and returned to the controller.

Is there another path through which the allow decision can be reached, without calling getPatchesForContainers()?

**Comment by jhart1685** [comment]
@guysports - ok, I guess that makes sense. Unfortunately, in our deployed Portieris, I don't see the `[image1:digest1]` stuff, either in _allow_ or _deny_ cases (with a simple signing policy). Which suggests something here is not working as intended.

**Comment by guysports** [comment]
@jhart1685 can you post the full portieris pod logs, and I'll see if I can work out what's awry. Thanks

**Comment by jhart1685** [comment]
@guysports - tell you what.. I'll make a more focused recreate, and then put it into a new issue.

**Pull request merged**
