### PR TITLE
Use cert-manager naming convention for portieris

### PR DESCRIPTION
**Pull request by josephdrichard**
Rename portieris certs from serverCert.pem and serverKey.pem to tls.crt
and tls.key, following the naming conventions used by cert-manager.
In combination with SkipSecretCreation=true, this allows using
cert-manager to generate portieris certs.

https://github.com/IBM/portieris/issues/59

Signed-off-by: Joseph Richard <jrichard@josephrichard.com>

### CODE REVIEW

**Comment by josephdrichard** [comment]
fixed email in commit message.

**Comment by josephdrichard** [comment]
Updated.  Added to changelog under 0.7.1.  When is 0.7.1 scheduled to be released?
Will now automatically create secret if UseCertManager is set, unless SkipSecretCreation (default: false) is also set.

**Comment by sjhx** [comment]
I am hoping to get 0.7.1 done in the next few days.

**Comment by josephdrichard** [comment]
Is there anything else needed for this to merge?

**Review by sjhx — APPROVED** [review]

**Pull request merged**
