### PR TITLE
Maintain tag in mutation

### PR DESCRIPTION
**Pull request by jeffb4**
Situation:
With standard portieris mutation, the image tag is stripped from a pod spec and the correct sha sum is injected. Operationally this is...okay. Images are pulled without problem because the tag is assumed `latest` and it is disregarded and the sha sum is used for pulling.

However, when doing helm upgrades, I have noticed that pod specs now fail portieris validation (and helm upgrade breaks) due to the missing tag being assumed to be `latest`, and there not being a valid signature for `latest` in the notary server.

Solution:
This patch (I remembered the tests this time, sorry about previous PR) maintains the tag during mutation. This works the same as previous, except operationally it's a little more visible ("here's the version tag we intended to be using") and it works as expected with helm upgrade

### CODE REVIEW

**Comment by sjhx** [comment]
I notice this is a revert of the commit which resolved this issue https://github.com/IBM/portieris/issues/90

The thinking when we removed the tag from the mutated image was that having a tag and a sha256 is potentially conflicting, the tag can change to point to another image whereas the sha256 is immutably the image we previously admitted.

If you think we should retain the tag as a record of history one way to do that would be to add an annotation. 

I am not convinced about the helm upgrade problem, surely on an upgrade the image will be new and be unmutated? The default policy until recently specified the tag which blocked upgrade, now resolved.
Is there really a problem with upgrade due to this?

**Comment by jeffb4** [comment]
The helm upgrade performed something such that portieris was trying to validate its own image specification, which it failed to do (because the tag assumed latest). I will try to get a log to paste into this PR. In my experience (and I see that crio only accepted the syntax only), tag+digest works fine, with the tag being ignored for the digest.

**Comment by jeffb4** [comment]
I was unable to get logs for this. It created a real issue for us (such that we had to use a build based off this branch).

Is there a design reason that Portieris mutates Deployments instead of generated Pods? Doing such might also mitigate the issue.

**Comment by sjhx** [comment]
We plan to go with the addition of annotation as a record of the original image name https://github.com/IBM/portieris/issues/169

**Pull request closed without merging**
